"""
reporting/signal_tracker.py

Logs every alert/signal generated by the system, then later checks realized
price action against the entry/stop/target levels to compute hit rate and
expectancy — broken down by category (Momentum Breakout, VCP Setup, etc).

This closes the feedback loop: without this, grade_signals.py's A/B/C grades
are untested opinions.

Storage here uses a flat CSV for simplicity. Swap for SQLite/a real DB once
volume grows past a few hundred signals — CSV will get unwieldy.
"""

from dataclasses import dataclass, asdict
from datetime import datetime, date
from pathlib import Path
from typing import Optional, Literal
import pandas as pd

LOG_PATH = Path("data/output/signal_log.csv")

Category = Literal[
    "Momentum Breakout",
    "Momentum-Pullback",
    "VCP Setup",
    "Turnaround",
    "Longterm Hold",
    "Avoid",
]

Outcome = Literal["target_hit", "stop_hit", "open", "expired_no_move"]


@dataclass
class SignalRecord:
    ticker: str
    category: Category
    grade: str  # "A", "B", "C" from grade_signals.py
    signal_date: str  # ISO date, e.g. "2026-07-04"
    entry_price: float
    stop_price: float
    target_price: float
    outcome: Outcome = "open"
    outcome_date: Optional[str] = None
    outcome_price: Optional[float] = None
    realized_r_multiple: Optional[float] = None  # (exit - entry) / (entry - stop)


def log_signal(record: SignalRecord, log_path: Path = LOG_PATH) -> None:
    """
    Append a new signal to the log. Call this at the moment grade_signals.py
    / Scheduler.py decides to send an alert — not before, not after.
    """
    log_path.parent.mkdir(parents=True, exist_ok=True)
    df_row = pd.DataFrame([asdict(record)])
    if log_path.exists():
        df_row.to_csv(log_path, mode="a", header=False, index=False)
    else:
        df_row.to_csv(log_path, mode="w", header=True, index=False)


def update_outcomes(
    log_path: Path = LOG_PATH,
    price_lookup_fn=None,
    expiry_days: int = 20,
) -> pd.DataFrame:
    """
    Walks all 'open' signals and checks whether price has since hit the
    target, hit the stop, or neither (marks 'expired_no_move' after
    expiry_days with no resolution).

    price_lookup_fn: a callable (ticker, start_date) -> pd.DataFrame of
    OHLC data since start_date. Wire this to your existing yfinance-backed
    metrics.py fetch so you're not duplicating the data-fetch/NaN-handling
    logic that's already been debugged there.
    """
    if price_lookup_fn is None:
        raise ValueError("price_lookup_fn is required — pass your yfinance fetch wrapper")

    df = pd.read_csv(log_path, parse_dates=["signal_date"])
    open_mask = df["outcome"] == "open"

    for idx in df[open_mask].index:
        row = df.loc[idx]
        prices = price_lookup_fn(row["ticker"], row["signal_date"])
        if prices is None or prices.empty:
            continue

        hit_target = (prices["High"] >= row["target_price"]).any()
        hit_stop = (prices["Low"] <= row["stop_price"]).any()
        days_elapsed = (pd.Timestamp.today() - row["signal_date"]).days

        if hit_target and hit_stop:
            # Ambiguous same-window hit — use whichever came first chronologically
            target_date = prices.loc[prices["High"] >= row["target_price"]].index[0]
            stop_date = prices.loc[prices["Low"] <= row["stop_price"]].index[0]
            if target_date <= stop_date:
                _resolve(df, idx, "target_hit", row["target_price"], target_date)
            else:
                _resolve(df, idx, "stop_hit", row["stop_price"], stop_date)
        elif hit_target:
            target_date = prices.loc[prices["High"] >= row["target_price"]].index[0]
            _resolve(df, idx, "target_hit", row["target_price"], target_date)
        elif hit_stop:
            stop_date = prices.loc[prices["Low"] <= row["stop_price"]].index[0]
            _resolve(df, idx, "stop_hit", row["stop_price"], stop_date)
        elif days_elapsed >= expiry_days:
            last_close = prices["Close"].iloc[-1]
            _resolve(df, idx, "expired_no_move", last_close, prices.index[-1])

    df.to_csv(log_path, index=False)
    return df


def _resolve(df: pd.DataFrame, idx, outcome: Outcome, exit_price: float, exit_date) -> None:
    row = df.loc[idx]
    r_multiple = (exit_price - row["entry_price"]) / (row["entry_price"] - row["stop_price"])
    df.loc[idx, "outcome"] = outcome
    df.loc[idx, "outcome_price"] = exit_price
    df.loc[idx, "outcome_date"] = str(exit_date)
    df.loc[idx, "realized_r_multiple"] = r_multiple


def performance_by_category(log_path: Path = LOG_PATH) -> pd.DataFrame:
    """
    The report that actually matters: hit rate and expectancy per category.
    Run this weekly. If a category's expectancy is consistently negative,
    that's your signal to fix or retire it — not gut feel.
    """
    df = pd.read_csv(log_path)
    closed = df[df["outcome"].isin(["target_hit", "stop_hit", "expired_no_move"])]

    def summarize(group):
        n = len(group)
        wins = (group["outcome"] == "target_hit").sum()
        hit_rate = wins / n if n else 0.0
        expectancy = group["realized_r_multiple"].mean()
        return pd.Series({
            "n_signals": n,
            "hit_rate": hit_rate,
            "avg_r_multiple": expectancy,
        })

    return closed.groupby("category").apply(summarize).sort_values(
        "avg_r_multiple", ascending=False
    )


# ---------------------------------------------------------------------------
# TODO wiring notes
# ---------------------------------------------------------------------------
# - Call log_signal() at the point grade_signals.py finalizes an A/B/C grade
#   and entry/stop/target, right before (or alongside) the Resend email send
#   in Scheduler.py.
# - Schedule update_outcomes() as a separate daily/nightly job, passing in
#   a thin wrapper around your existing metrics.py yfinance fetch.
# - Schedule performance_by_category() weekly; consider emailing yourself
#   this summary the same way alerts go out — treat your own track record
#   as its own dashboard.
# - Once volume grows, migrate storage to SQLite: pandas read/write to CSV
#   under concurrent Scheduler.py runs risks race conditions.